### ISSUE TITLE
Rollup failed to resolve static asset in the public dir during production build

### ISSUE THREAD

**Issue by JustDylan23** [lhapaipai/vite-plugin-symfony#12]
### The issue
during production builds assets with an absolute path are not ignored by Vite and it tries to handle it as relative asset.

I reference it like this in my Vue template: `<img src="/favicon.png" />`, which works fine via the dev server but breaks during a production build.

the favicon is located at `public/favicon.png`.

### Additional information
```
[vite]: Rollup failed to resolve import "/favicon.png" from "assets/layout/components/AppHeader.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "/favicon.png" from "assets/layout/components/AppHeader.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///home/dylan/development/sonicgetaway/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
    at onwarn (file:///home/dylan/development/sonicgetaway/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
    at Object.onwarn (file:///home/dylan/development/sonicgetaway/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///home/dylan/development/sonicgetaway/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///home/dylan/development/sonicgetaway/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```

this is my vite config:
```js
import { defineConfig } from 'vite';
import symfonyPlugin from 'vite-plugin-symfony';
import vue from '@vitejs/plugin-vue';
import eslintPlugin from 'vite-plugin-eslint';
import { resolve } from 'path';

export default defineConfig({
  plugins: [
    symfonyPlugin(),
    vue(),
    eslintPlugin(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './assets/'),
      '~bootstrap': 'bootstrap',
    },
  },
  build: {
    rollupOptions: {
      input: {
        app: './assets/app.js',
      },
    },
  },
});
```
package.json:
```json
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "lint": "eslint --ext .js,.vue --ignore-path .gitignore --fix assets"
    },
    "license": "UNLICENSED",
    "devDependencies": {
        "@vitejs/plugin-vue": "3.2.0",
        "eslint": "^8.29.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-vue": "^9.8.0",
        "prettier": "^2.8.1",
        "sass": "^1.56.2",
        "vite": "^3.2.5",
        "vite-plugin-eslint": "^1.8.1",
        "vite-plugin-symfony": "^0.7.0"
    },
    "dependencies": {
        "@popperjs/core": "^2.11.6",
        "bootstrap": "^5.2.3",
        "bootstrap-icons": "^1.10.2",
        "vue": "^3.2.45",
        "vue-router": "^4.1.6"
    }
}
```

**Comment by JustDylan23** [comment]
I don't know exactly what changed. But after doing a completely fresh install everything seems to work as intended. Closing this for now.
