### ISSUE TITLE
Error: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by 3PSY0N** [lhapaipai/vite-plugin-symfony#18]
Hi,
i just started fresh install of symfony and installed `pentatrion/vite-bundle` (wich install the version 0.7.6) and i have this error below

```js
failed to load config from /home/3p/website/vite.config.js
error during build:
  Error [ERR_REQUIRE_ESM]: require() of ES Module /home/3p/website/node_modules/vite-plugin-symfony/dist/index.js from /home/3p/website/vite.config.js not supported.
  Instead change the require of index.js in /home/3p/website/vite.config.js to a dynamic import() which is available in all CommonJS modules.
  at Object._require.extensions.<computed> [as .js] (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:63989:17)
    at Object.<anonymous> (/home/3p/website/vite.config.js:36:42)
        at Object._require.extensions.<computed> [as .js] (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:63986:24)
            at loadConfigFromBundledFile (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:63994:21)
            at loadConfigFromFile (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:63852:34)
            at async resolveConfig (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:63466:28)
            at async build (file:///home/3p/website/node_modules/vite/dist/node/chunks/dep-79892de8.js:46088:20)
            at async CAC.<anonymous> (file:///home/3p/website/node_modules/vite/dist/node/cli.js:813:9)
```

vite.config.js

```js
import { defineConfig } from "vite";
import symfonyPlugin from "vite-plugin-symfony";

export default defineConfig({
    plugins: [
        symfonyPlugin(),
    ],
    build: {
        rollupOptions: {
            input: {
                app: "./assets/app.js"
            },
        }
    },
});
```

package.json

```json
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "license": "UNLICENSED",
    "devDependencies": {
        "vite": "^4.0",
        "vite-plugin-symfony": "^0.7.2"
    }
}
```
❯ node --version
`v16.19.1`
❯ npm --version
`8.19.3`

I have already installed this bundle several times without error in the past (the last time was 2 months ago), and now I don't know what changed to make it not work anymore.

PS: I tried to use the package.lock from my previous project from two months ago, and I don't have any error during compilation. ("vite-plugin-symfony": "0.7.5") is actually working.

Thank you

**Comment by lhapaipai** [comment]
hi @3PSY0N,
you have to set in your `package.json`
```diff
{
+  "type": "module"
}
```

**Comment by lhapaipai** [comment]
Hum hum It seems to work but I'm not sure I used the best practice...
```ts
let pluginDir;
try {
  pluginDir = dirname(__dirname);
} catch (e) {
  pluginDir = dirname(dirname(fileURLToPath(import.meta.url)));
}
```

Have you got any idea ?

**Comment by 3PSY0N** [comment]
Ok so, looks like the update `"vite-plugin-symfony": "^0.7.7"` is working on a new test project without the `'type': 'module'` !

Merci beaucoup ! <3

**Comment by lhapaipai** [comment]
de rien :smile:
