### ISSUE TITLE
Maximum call stack size exceeded during vite build

### ISSUE THREAD

**Issue by C010UR** [lhapaipai/vite-plugin-symfony#20]
If i use more than 5 manual chunks, i get ` RangeError: Maximum call stack size exceeded`

This will break after build:
```js
manualChunks: {
          elementplus: ['element-plus', '@element-plus/icons-vue'],
          axios: ['axios', 'axios-cache-interceptor'],
          modules: ['lodash', 'path', 'qs', 'validator'],
          vue: ['vue-router', 'pinia', '@vueuse/core'],
          components: ['assets/components/pages/index.ts', 'assets/components/tags/index.ts'],
          composables: ['assets/composables/index.ts'],
          views: ['assets/views/index.ts'],
        },
```

And this will not:
```js
manualChunks: {
          elementplus: ['element-plus', '@element-plus/icons-vue'],
          axios: ['axios', 'axios-cache-interceptor'],
          modules: ['lodash', 'path', 'qs', 'validator'],
          vue: ['vue-router', 'pinia', '@vueuse/core'],
          views: ['assets/views/index.ts'],
        },
```

`composables`, `components`, and `views` don't take more than 100kb after they are built.
The issue is also inconsistent, if i run `vite build` on local machine, i can use more chunks, than during docker build.

Log:
```
#0 0.999 > build
#0 0.999 > vite build
#0 0.999
#0 1.381 [unplugin-vue-components] no components found
#0 1.381 vite v4.3.8 building for production...
#0 1.780 transforming...
#0 26.16 ✓ 1956 modules transformed.
#0 26.85 rendering chunks...
#0 27.50 [symfony] Maximum call stack size exceeded
#0 27.50 ✓ built in 26.11s
#0 27.50 error during build:
#0 27.50 RangeError: Maximum call stack size exceeded
#0 27.50     at Array.values (<anonymous>)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:174:45)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
#0 27.50     at resolveEntrypoint (/srv/app/node_modules/vite-plugin-symfony/dist/index.js:179:58)
```

I use `vite 4.3` and `vite-plugin-symfony 0.7.8`

**Comment by lhapaipai** [comment]
Hi @C010UR, it seems that there is a circular reference between your chunks. v3.3.1 should fix this
