### ISSUE TITLE
`Error: Dynamic require of "os" is not supported`

### ISSUE THREAD

**Issue by D3strukt0r** [lhapaipai/vite-plugin-symfony#27]
4.3.0 is the last working version. with 4.3.1 and 4.3.2 I get the following when I run the vite dev server

below is my bash history when trying 4.3.0 and 4.3.1

```
www-data@46c1251a9358:/app$ yarn add vite-plugin-symfony@"^4.0.1 <=4.3.0"
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > vite-plugin-chunk-split@0.4.7" has incorrect peer dependency "vite@^3.1.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ vite-plugin-symfony@4.3.0
info All dependencies
└─ vite-plugin-symfony@4.3.0
Done in 24.35s.
www-data@46c1251a9358:/app$ yarn dev
yarn run v1.22.19
$ cross-env BROWSERSLIST_ENV=development vite
Forced re-optimization of dependencies

  VITE v4.4.11  ready in 1067 ms

  ➜  Local:   https://localhost:5173/build/
  ➜  Network: https://172.18.0.4:5173/build/
  ➜  press h to show help
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
www-data@46c1251a9358:/app$ yarn add vite-plugin-symfony@"^4.0.1 <=4.3.1"
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > vite-plugin-chunk-split@0.4.7" has incorrect peer dependency "vite@^3.1.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ vite-plugin-symfony@4.3.1
info All dependencies
└─ vite-plugin-symfony@4.3.1
Done in 25.08s.
www-data@46c1251a9358:/app$ yarn dev
yarn run v1.22.19
$ cross-env BROWSERSLIST_ENV=development vite
failed to load config from /app/vite.config.js
error when starting dev server:
Error: Dynamic require of "os" is not supported
    at file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:12:9
    at node_modules/fast-glob/out/utils/path.js (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:118:15)
    at __require2 (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:18:50)
    at node_modules/fast-glob/out/utils/index.js (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:3480:17)
    at __require2 (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:18:50)
    at node_modules/fast-glob/out/managers/tasks.js (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:3498:17)
    at __require2 (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:18:50)
    at node_modules/fast-glob/out/index.js (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:5493:23)
    at __require2 (file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:18:50)
    at file:///app/node_modules/vite-plugin-symfony/dist/index.mjs:5592:32
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lhapaipai** [comment]
hi @D3strukt0r 
Please, can you give me a way to reproduce your issue...
your os, your node version, your vite config file.

**Comment by D3strukt0r** [comment]
@lhapaipai
The OS is a PHP Debian (Buster) image where we install Node.js after the fact (see https://github.com/iwf-web/docker-phpfpm/blob/releases/PHP-FPM-8.2/docker/build/Dockerfile)

Node.js is v18.17.1

Vite config
```js
import fs from 'fs';
import * as dotenv from 'dotenv';
import {defineConfig} from 'vite';
import {chunkSplitPlugin} from 'vite-plugin-chunk-split';
import react from '@vitejs/plugin-react';
import symfonyPlugin from 'vite-plugin-symfony';
import browserslistToEsbuild from 'browserslist-to-esbuild';
import viteRestart from 'vite-plugin-restart';
import i18nHotReload from './assets/vite-plugins/i18n-hot-reload';
import svgr from 'vite-plugin-svgr';
import {blurHash} from 'vite-plugin-blurhash';

dotenv.config();

export default defineConfig(({command}) => ({
  plugins: [
    chunkSplitPlugin({
      customChunk: ({file}) => {
        // Extract each node_modules package into a separate chunk in "js/npm/(user-)package".
        // Regex taken from: https://github.com/npm/validate-npm-package-name/blob/main/lib/index.js#L3
        const match = file.match(/node_modules\/(?:@([^\/]+?)[\/])?([^\/]+)/);
        if (match) {
          const name = match[1] ? `${match[1]}-${match[2]}` : match[2];
          return `npm/${name}`;
        }
        if (file === 'assets/utils/init-monaco.js') {
          return 'monaco/init';
        }
        return null;
      },
    }),
    svgr(),
    // Either improve this plugin, so it doesn't regenerate blurhashes on every start, or simply uncomment when needed
    // (when an image is added).
    // blurHash({
    //   imageDir: '/assets/img',
    //   mapPath: '/assets/img/blurhash-map.json',
    // }),
    react(),
    symfonyPlugin(),
    viteRestart({
      reload: ['templates/*.twig'],
    }),
    i18nHotReload(),
  ],
  base: '/build/',
  build: {
    target: browserslistToEsbuild(),
    outDir: './public/build',
    rollupOptions: {
      input: {
        'app': './assets/app.jsx',
      },
      output: {
        assetFileNames: (assetInfo) => {
          // Place asset in each corresponding folder "build/{img,font,etc.}/*".
          const info = assetInfo.name.split('.');
          let extType = info[info.length - 1];
          if (/png|jpe?g|svg|gif|tiff|bmp|ico|avif|webp/i.test(extType)) {
            extType = 'img';
          } else if (/woff2?|otf|ttf|eot/.test(extType)) {
            extType = 'font';
          }
          return `${extType}/[name].[hash][extname]`;
        },
        chunkFileNames: 'js/[name].[hash].js',
        entryFileNames: 'js/[name].[hash].js',
      },
    },
    manifest: true,
  },
  server: {
    host: '0.0.0.0',
    strictPort: true,
    https: {
      // Get certificates if we are not building (CI has no certificates)
      key: command === 'build' ? null : fs.readFileSync('docker/run/certificates/key.pem'),
      cert: command === 'build' ? null : fs.readFileSync('docker/run/certificates/cert.pem'),
    },
    watch: {
      ignored: ['**/.idea/**', '**/tests/**', '**/var/**', '**/vendor/**'],
    },
    origin: `https://${process.env.APP_URL}:5173`,
  },
  // Needed for antd
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  },
}));
```

and the package.json

```json
{
  "license": "UNLICENSED",
  "type": "module",
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/pro-light-svg-icons": "^6.2.1",
    "@fortawesome/pro-regular-svg-icons": "^6.2.1",
    "@fortawesome/pro-solid-svg-icons": "^6.2.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@monaco-editor/react": "^4.4.6",
    "@redux-devtools/extension": "^3.2.5",
    "@reduxjs/toolkit": "^1.9.0",
    "@sentry/browser": "^7.19.0",
    "@tiptap/core": "^2.0.2",
    "@tiptap/extension-character-count": "^2.0.2",
    "@tiptap/extension-color": "^2.0.2",
    "@tiptap/extension-document": "^2.0.2",
    "@tiptap/extension-link": "^2.0.2",
    "@tiptap/extension-list-item": "^2.0.2",
    "@tiptap/extension-paragraph": "^2.0.2",
    "@tiptap/extension-placeholder": "^2.0.2",
    "@tiptap/extension-text": "^2.0.2",
    "@tiptap/extension-text-style": "^2.0.2",
    "@tiptap/pm": "^2.0.2",
    "@tiptap/react": "^2.0.2",
    "@tiptap/starter-kit": "^2.0.2",
    "@vitejs/plugin-react": "^4.0.0",
    "add": "^2.0.6",
    "antd": "^4.24.1",
    "blurhash": "^2.0.5",
    "browserslist-to-esbuild": "^1.2.0",
    "chalk": "^5.2.0",
    "classnames": "^2.3.2",
    "core-js": "^3.26.0",
    "cross-env": "^7.0.3",
    "dayjs": "^1.11.6",
    "dotenv": "^16.0.3",
    "eslint": "^8.27.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "i18next": "^23.2.11",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-http-backend": "^2.0.1",
    "interweave": "^13.0.0",
    "less": "^4.1.3",
    "lodash": "^4.17.21",
    "monaco-editor": "^0.44.0",
    "object-hash": "^3.0.0",
    "prop-types": "^15.8.1",
    "query-string": "^8.1.0",
    "rc-picker": "^3.3.1",
    "react": "^18.2.0",
    "react-blurhash": "^0.3.0",
    "react-dom": "^18.2.0",
    "react-dropdown": "^1.11.0",
    "react-i18next": "^13.0.2",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.4.3 <6.11.0",
    "react-text-truncate": "^0.19.0",
    "react-transition-group": "^4.4.5",
    "recharts": "^2.5.0",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.2",
    "vite": "^4.1.2",
    "vite-plugin-blurhash": "^0.2.0",
    "vite-plugin-chunk-split": "^0.4.7",
    "vite-plugin-restart": "^0.3.1",
    "vite-plugin-svgr": "^4.1.0",
    "vite-plugin-symfony": "^4.0.1 <4.3.1 || ^4.3.3"
  },
  "scripts": {
    "dev": "cross-env BROWSERSLIST_ENV=development vite",
    "build": "vite build"
  },
  "private": true
}
```

**Comment by lhapaipai** [comment]
thanks ! it seems its a commonjs/esm issue, I will fix it.

**Comment by D3strukt0r** [comment]
@lhapaipai 
```
[......sorry i cleared my console for the install, but I have v4.3.3 running here..........]
www-data@fe5a60a02993:/app$ yarn dev
yarn run v1.22.19
$ cross-env BROWSERSLIST_ENV=development vite
failed to load config from /app/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fast-glob' imported from /app/node_modules/vite-plugin-symfony/dist/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
www-data@fe5a60a02993:/app$ yarn add fast-glob
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > vite-plugin-chunk-split@0.4.7" has incorrect peer dependency "vite@^3.1.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ fast-glob@3.3.1
info All dependencies
├─ fast-glob@3.3.1
├─ glob-parent@5.1.2
└─ merge2@1.4.1
Done in 28.52s.
[...........the module "sharp" failed here, so I readded it, but it has nothing to do with this issue...........]
www-data@fe5a60a02993:/app$ yarn dev
yarn run v1.22.19
$ cross-env BROWSERSLIST_ENV=development vite
Forced re-optimization of dependencies

  VITE v4.4.11  ready in 2385 ms

  ➜  Local:   https://localhost:5173/build/
  ➜  Network: https://172.18.0.6:5173/build/
  ➜  press h to show help
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
www-data@fe5a60a02993:/app$
```

now that you added it as an external dependency, it simply failed here. had to add that package. I don't think that's what you want though (or the user of your library) :)

**Comment by lhapaipai** [comment]
yes.... so I added has dependency, can you check v4.3.4... :smiley: sorry

**Comment by D3strukt0r** [comment]
np :)
ok seems to just work now, thanks 👍🏻
