### ISSUE TITLE
stimulus and only vue-ux can't resolve "virtual:symfony/controlles"

### ISSUE THREAD

**Issue by Lappihuan** [lhapaipai/vite-plugin-symfony#33]
### vite-plugin-symfony version

6.1.1

### vite-bundle version

6.1.1

### your OS, node version, Symfony version, PHP version

Linux, node 18.17.1, Symfony 6.3.8, PHP8.2

### Description

when executing `npm run dev` we get the error:
```
✘ [ERROR] Could not resolve "virtual:symfony/controllers"

    node_modules/.pnpm/vite-plugin-symfony@6.1.1_vite@4.5.0/node_modules/vite-plugin-symfony/dist/stimulus/helpers/index.mjs:8:34:
      8 │ import thirdPartyControllers from "virtual:symfony/controllers";
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:symfony/controllers" as external to exclude it from the bundle,
  which will remove this error.

/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/vite-plugin-symfony@6.1.1_vite@4.5.0/node_modules/vite-plugin-symfony/dist/stimulus/helpers/index.mjs:8:34: ERROR: Could not resolve "virtual:symfony/controllers"
    at failureErrorWithLog (/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at /node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 34,
        file: 'node_modules/.pnpm/vite-plugin-symfony@6.1.1_vite@4.5.0/node_modules/vite-plugin-symfony/dist/stimulus/helpers/index.mjs',
        length: 29,
        line: 8,
        lineText: 'import thirdPartyControllers from "virtual:symfony/controllers";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "virtual:symfony/controllers" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "virtual:symfony/controllers"'
    }
  ],
  warnings: []
}

```

### How to reproduce

When following the base installation: https://symfony-vite.pentatrion.com/guide/installation.html
And stimulus / Symfony UX: https://symfony-vite.pentatrion.com/guide/stimulus-symfony-ux.html
With only vue-ux

**Comment by lhapaipai** [comment]
have you set the `stimulus: true` vite-plugin-symfony option ?

```diff
export default defineConfig({
  plugins: [
    symfonyPlugin({
+      stimulus: true 
    }),
  ],

  build: {
    rollupOptions: {
      input: {
        "app": "./assets/app.js",
      }
    }
  },
});
```

**Comment by Lappihuan** [comment]
Yes, setting that boolean did not affect the error at all.

**Comment by lhapaipai** [comment]
for the moment I've found this.
```js
export default defineConfig({
    optimizeDeps: {
        exclude: ["virtual:symfony/controllers"]
    },
    plugins: [
        symfonyPlugin({
	    stimulus: true
	}),
	vuePlugin(),
    ],
    build: {
        rollupOptions: {
            input: {
                app: "./assets/app.js"
            },
        }
    },
});
```
but I need more investigation to understand why this is not happening in the development environment.
Thanks for your feedback

**Comment by Lappihuan** [comment]
We also tried this, but this just hides the error from the server start.
When you load the page you get the same error via the hmr-console from vite.

**Comment by lhapaipai** [comment]
I think it's fixed on v6.1.2 
working example
https://github.com/lhapaipai/stimulus-uxvue-REPRODUCE
need : `npm i --force`
warning : stimulus feature is experimental and still in development and I've changed the `assets/bootstrap.js` content
```js
import { startStimulusApp, registerControllers, registerVueControllerComponents } from "vite-plugin-symfony/stimulus/helpers"

registerVueControllerComponents(import.meta.glob('./vue/controllers/**/*.vue')) 
const app = startStimulusApp();
registerControllers(app, import.meta.glob('./controllers/*_(lazy)\?controller.[jt]s(x)\?'))
```

**Comment by lhapaipai** [comment]
if you want a complete example, use the stimulus playground :-)

```bash
git clone https://github.com/lhapaipai/symfony-vite-dev.git
cd symfony-vite-dev
make install
cd playground/stimulus
composer install
npm i

symfony serve
npm run dev

# go !
```

**Comment by Lappihuan** [comment]
@lhapaipai everything seems to be working now.
thank you for the awesome work! 🥳
